# Generated by Django 4.2.2 on 2023-06-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=255)),
                ('academic_program_name', models.CharField(max_length=255)),
                ('seat_type', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('opening_rank', models.IntegerField()),
                ('closing_rank', models.IntegerField()),
                ('year', models.IntegerField()),
                ('round', models.IntegerField()),
                ('has_p', models.BooleanField()),
            ],
        ),
    ]
